.\"
.\" cinnamon-session-properties manual page.
.\" (C) 2009-2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH GNOME-SESSION-PROPERTIES 1 "GNOME"
.SH NAME
cinnamon-session-properties \- Configure applications to start on login
.SH SYNOPSIS
.B cinnamon-session-properties
.SH DESCRIPTION
.PP
The \fIcinnamon-session-properties\fP program enables the users to
configure what applications should be started on login, in addition to
the default startup applications configured on the system.
.PP
It also proposes an interface to save a snapshot of the currently
running applications so that they can automatically be restored to
their current state on your next GNOME session.
.SH SEE ALSO
.BR cinnamon-session(1)
.BR cinnamon-session-save(1)
